apiVersion: v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - name: example-application
        image: gcr.io/gitopsdemo-314411/example-application
        ports:
        - containerPort: 8080
